spring:
  devtools:
    remote:
      secret: 123
  application:
    name: @project.name@
    version: @project.version@
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador?useSSL=false
    username: root
    password: miniautorizador
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
server:
  port: 8080
  servlet:
    context-path: /mini-autorizador/v1
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
